-- Drop the existing ORDERS_FRESH table if it exists
DROP TABLE IF EXISTS NWT_SCHEMA.ORDERS_FRESH;

CREATE TABLE NORTHWIND_DATA.NWT_SCHEMA.ORDERS_FRESH (
      ORDERID NUMBER(38,0),
      CUSTOMERID VARCHAR,
      EMPLOYEEID NUMBER(38,0),
      ORDERDATE DATE,
      REQUIREDDATE DATE,
      SHIPPEDDATE DATE,
      SHIPVIA NUMBER(38,0),
      FREIGHT NUMBER(38,0),
      SHIPNAME VARCHAR,
      SHIPADDRESS VARCHAR,
      SHIPCITY VARCHAR,
      SHIPREGION VARCHAR,
      SHIPPOSTALCODE VARCHAR,
      SHIPCOUNTRY VARCHAR
     );

