-- Identify duplicate entries in EMPLOYEE_TERRITORIES
-- Find rows with duplicate EMPLOYEEID in EMPLOYEE_TERRITORIES
-- Remove duplicate entries in EMPLOYEE_TERRITORIES

SELECT EMPLOYEEID, TERRITORYID, COUNT(*)
FROM NORTHWIND_DATA.NWT_SCHEMA.EMPLOYEE_TERRITORIES
GROUP BY EMPLOYEEID, TERRITORYID
HAVING COUNT(*) > 1;

DELETE FROM NORTHWIND_DATA.NWT_SCHEMA.EMPLOYEE_TERRITORIES
WHERE (EMPLOYEEID, TERRITORYID) IN (
    SELECT EMPLOYEEID, TERRITORYID
    FROM NORTHWIND_DATA.NWT_SCHEMA.EMPLOYEE_TERRITORIES
    GROUP BY EMPLOYEEID, TERRITORYID
    HAVING COUNT(*) > 1
);