-- Identify duplicate entries in EMPLOYEE_TERRITORIES
-- Find rows with duplicate EMPLOYEEID in EMPLOYEE_TERRITORIES
-- Remove duplicate entries in EMPLOYEE_TERRITORIES

DELETE FROM NORTHWIND_DATA.NWT_SCHEMA.EMPLOYEE_TERRITORIES
WHERE (EMPLOYEEID, TERRITORYID) IN (
    SELECT EMPLOYEEID, TERRITORYID
    FROM (
        SELECT EMPLOYEEID, TERRITORYID,
               ROW_NUMBER() OVER (PARTITION BY EMPLOYEEID, TERRITORYID ORDER BY (SELECT NULL)) AS RowNum
        FROM NORTHWIND_DATA.NWT_SCHEMA.EMPLOYEE_TERRITORIES
    ) AS duplicates
    WHERE RowNum > 1
);