-- Identify duplicate entries in EMPLOYEE_TERRITORIES
-- Find rows with duplicate EMPLOYEEID in EMPLOYEE_TERRITORIES
SELECT EMPLOYEEID, COUNT(*)
FROM NORTHWIND_DATA.NWT_SCHEMA.RAW_EMPLOYEEs
GROUP BY EMPLOYEEID
HAVING COUNT(*) > 1;