SHOW IMPORTED KEYS IN 
NORTHWIND_DATA.NWT_SCHEMA.PRODUCT

SHOW IMPORTED KEYS IN 
NORTHWIND_DATA.NWT_SCHEMA.ORDERS

SHOW IMPORTED KEYS IN 
NORTHWIND_DATA.NWT_SCHEMA.TERRITORY

SHOW IMPORTED KEYS IN 
NORTHWIND_DATA.NWT_SCHEMA.EMPLOYEE_TERRITORIES

SHOW IMPORTED KEYS IN 
NORTHWIND_DATA.NWT_SCHEMA.ORDER_DETAIL