name: Import Fresh Orders

on:
  push:
    branches:
      - main
    paths:
      - 'migrations/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  import_fresh_orders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Snowflake Queries
        uses: anecdotes-ai/snowflake-query@v1.2
        id: run_snowflake_queries
        with:
          snowflake_account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          snowflake_warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          snowflake_username: ${{ secrets.SNOWFLAKE_USER }}
          snowflake_password: ${{ secrets.SNOWFLAKE_PASSWORD }}

          queries: |
            -- Create external stage for GitHub CSV file
            CREATE OR REPLACE EXTERNAL STAGE my_external_stage
            URL = 'https://github.com/just4jc/Northwind-Traders-Dataset/blob/main/order_fresh.csv';

            -- Drop existing ORDERS table (if exists)
            DROP TABLE IF EXISTS NORTHWIND_DATA.NWT_SCHEMA.ORDERS_FRESH;

            -- Create the ORDERS table
            CREATE TABLE NORTHWIND_DATA.NWT_SCHEMA.ORDERS_FRESH (
              ORDERID NUMBER(38,0),
              CUSTOMERID VARCHAR,
              EMPLOYEEID NUMBER(38,0),
              ORDERDATE DATE,
              REQUIREDDATE DATE,
              SHIPPEDDATE DATE,
              SHIPVIA NUMBER(38,0),
              FREIGHT NUMBER(38,0),
              SHIPNAME VARCHAR,
              SHIPADDRESS VARCHAR,
              SHIPCITY VARCHAR,
              SHIPREGION VARCHAR,
              SHIPPOSTALCODE VARCHAR,
              SHIPCOUNTRY VARCHAR
            );

            -- Copy data from the external stage into the table
            COPY INTO NORTHWIND_DATA.NWT_SCHEMA.ORDERS_FRESH
            FROM @my_external_stage/order_fresh.csv
            FILE_FORMAT = (TYPE = 'CSV' FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER = 1)
            ON_ERROR = 'CONTINUE';

            SELECT CURRENT_VERSION();
