name: Update orders_fresh table in Snowflake

on:
  push:
    branches:
      - main
    paths:
      - 'migrations/**'
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-orders-fresh:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Use Python 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas snowflake-connector-python snowflake-sqlalchemy

    - name: Download orders_fresh.csv and update Snowflake table
      env:
        SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
        SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
        SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
      run: |
        python migrations/update_snowflake.py
