name: Import Fresh Orders

on:
  push:
    paths:
      - 'NWT_ADO/migration/overwriting_fresh_orders.sql'
      - 'just4jc/Northwind-Traders-Dataset/order_fresh.csv'

jobs:
  import_fresh_orders:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Snowflake CLI
      uses: snowflakedb/snowflake-connector-python-action@v1
      with:
        SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
        SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
        SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
        SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

    - name: Run SQL script
      run: snowsql -f NWT_ADO/migration/overwriting_fresh_orders.sql
