name: Import Fresh Orders

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight

jobs:
  import_fresh_orders:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Snowflake CLI
      uses: snowflakedb/snowflake-connector-python-action@v1
      with:
        account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        database: ${{ secrets.SNOWFLAKE_DATABASE }}
        schema: NWT_SCHEMA
        role: ${{ secrets.SNOWFLAKE_ROLE }}
        username: ${{ secrets.SNOWFLAKE_USERNAME }}
        password: ${{ secrets.SNOWFLAKE_PASSWORD }}

    - name: Run SQL script
      run: snowsql -f NWT_ADO/migration/overwriting_fresh_orders.sql

